<?php
/**
 * Slide 06 — Gate / Decision: Bogactwo to decyzja
 *
 * @var bool $is_active
 * @package SB_Slider
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="sb-slide sb-slide-6<?php echo $is_active ? ' sb-active' : ''; ?>">
    <!-- Falling money symbols (generated by JS) -->
    <div class="sb-money-rain"></div>

    <!-- Gate image -->
    <div class="sb-gate-container">
        <img src="<?php echo esc_url( 'https://lekcjewartemiliony.pl/wp-content/uploads/2026/02/drzwi.png' ); ?>" alt="Gate" class="sb-gate-image">
    </div>

    <!-- Text content -->
    <div class="sb-content-overlay">
        <div class="sb-left-text">
            <div class="sb-top-label">Zmiana zaczyna się od decyzji</div>
            <h2>Bogactwo<br>to decyzja.</h2>
            <p class="sb-subtitle-gold">Reszta to strategia.</p>
        </div>

        <div class="sb-right-text">
            <p class="sb-right-description">Zarabianie to kompetencja.<br>Oszczędzanie to strategia.<br>Milion to efekt.</p>
            <div class="sb-cta-container">
                <a href="#" class="sb-cta-button">Zaczynam zmianę</a>
            </div>
        </div>
    </div>
</div>
